# Lock the screen with a custom background image
swaylock \
  --indicator \
  --clock \
  --timestr="%H:%M:%S" \
  --datestr="%A, %d %B %Y" \
  --font=monospace \
  --font-size=48 \
  --indicator-radius=100 \
  --indicator-thickness=7 \
  --ring-color=285577 \
  --key-hl-color=d23c3d \
  --line-color=00000000 \
  --inside-color=00000000 \
  --separator-color=00000000 \
  --grace=2 \
  --fade-in=0.2 \
  --effect-blur=7x5 \
  --effect-vignette=0.5:0.5 \
  --screenshots \
  --daemonize \
  --indicator
